info:
  app:
    name: Autuacao
    description: STFDigital Autuacao-Autuacao 
server.port: 8092

spring.activiti.database-schema: activitiautuacao
  
integracao.url-ambiente: http://sistemast.stf.jus.br

spring:
  cloud:
    stream:
      rabbit:
        bindings:
          "[documento.recebido]":
            consumer:
              autoBindDlq: true
              republishToDlq: true
