spring: 
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/xe
    username: usuariodocuments
    password: oracle
    initialize: false
    hikari:
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
 
flyway: 
  url: jdbc:oracle:thin:@oracle:1521/xe
  user: flywaydocuments
  password: oracle
  locations: 
   - classpath:db/migration
   - classpath:db/structure/flyway/callbacks

onlyoffice: 
  server:
    address: https://stfdigital2:30443
  integration:
    address: onlyoffice
    port: 443
  documentserver:
    host: stfdigital2.stf.jus.br
    port: 30790
