server:
  port: 8094

spring:
  data:
    cassandra:
      port: 9042
      keyspace-name: documents
      contact-points: cassandra
  datasource:
    hikari:
      connection-timeout: 120000
      maximum-pool-size: 20
      max-lifetime: 120000
      pool-name: documents-ds
