spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/xe
    username: usuarioidentidades
    password: oracle
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

flyway:
  url: jdbc:oracle:thin:@oracle:1521/xe
  user: flywayidentidades
  password: oracle
  locations:
    - classpath:db/migration
- classpath:db/structure/flyway/callbacks
