spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/xe
    username: usuariorecebimento
    password: oracle
    initialize: false
    hikari:
      maximum-pool-size: 2
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    
flyway:
  url: jdbc:oracle:thin:@oracle:1521/xe
  user: flywayrecebimento
  password: oracle
  locations:
   - classpath:db/migration
   - classpath:db/structure/flyway/callbacks
